// PUT http://localhost:3001/api/persons/772264134
PUT https://limitless-everglades-27152.herokuapp.com/api/persons/116401786
Content-Type: application/json

{
  "name": "Muutettu hemmo",
  "number": "666"
}